### ISSUE TITLE
MonoGameEffect.UpdateEffectParameters doesn't handle null effect

### ISSUE THREAD

**Issue by jbhaywood** [EmptyKeys/UI_Engines#11]
There are two places before this call where the effect can become null. But the method itself assumes that it never is, potentially causing a crash. A simple null check before doing anything else would prevent that.

(The reason I hit this was because I had to switch to the MonoGame OpenGL dll instead of Window8 in the UI samples project. Using the Windows8 assembly was causing other null reference crashes.)

**Comment by EmptyKeys** [comment]
thanks for info, i will include fix in the next version

**Comment by EmptyKeys** [comment]
fix done, will be in next version
