### ISSUE TITLE
Many needed source files are missing from the repo.

### ISSUE THREAD

**Issue by SirDragonClaw** [EmptyKeys/UI_Engines#12]
Many needed source files are missing from the repo. Whats the work around for this?

![image](https://user-images.githubusercontent.com/2770203/35950825-93972f88-0ccc-11e8-916c-e1c6554f2e1e.png)

**Comment by SirDragonClaw** [comment]
I have added both the core and monogame userinterface projects and then get these compile time errors because no project actually includes the controls.

**Comment by EmptyKeys** [comment]
Hi, this repo is only for UI Engines support. The rest of Empty Keys UI library is not open source.

You can get the latest version of UI library on https://www.nuget.org/packages/EmptyKeysUI_MonoGame/

**Comment by SirDragonClaw** [comment]
I cannot use that as it doesn't work with the latest monogame desktop build with .net 4.6.2

So I guess that means this library is useless for most people then. Whats the point of having a nuget package that is incompatible with most versions of monogame?

**Comment by EmptyKeys** [comment]
It works perfectly fine with latest .Net and latest MonoGame version. So be specific why you can not use NuGet package please.
