### ISSUE TITLE
Input method problems

### ISSUE THREAD

**Issue by esengine** [EmptyKeys/UI_Engines#13]
Hello I have encountered a problem. I can't use my input method to type in the input box. can you help me?

**Comment by esengine** [comment]
I use MonoGame

**Comment by EmptyKeys** [comment]
Did you try examples here https://github.com/EmptyKeys/UI_Examples ?

**Comment by esengine** [comment]
Yes, I cannot use the input method to enter multi-byte characters in this example.

**Comment by esengine** [comment]
This input box appears to be what you typed and he directly displays it, I hope it can call the system's IME to enter

**Comment by EmptyKeys** [comment]
If you mean chinese/japanese or similar, I doubt that MonoGame supports IME. Ask on MonoGame GitHub.

**Comment by esengine** [comment]
Thank you, I'll ask monogame

**Comment by esengine** [comment]
https://github.com/MonoGame/MonoGame/issues/6347

Monogame says there is a way to replace ime

**Comment by EmptyKeys** [comment]
Let's hope they will implement that one day.
