### ISSUE TITLE
Image not loaded into button content

### ISSUE THREAD

**Issue by mseress** [EmptyKeys/UI_Engines#15]
A little introduction to the issue:
I want to make a cross-platform game on top of MonoGame in which there are a lot of clickable sprites that have static/animated textures and they may have a generic shape which means their hit test area will be an arbitrary polygon. Empty Keys seems to be something that can handle such a thing, so as a first step I tried to customize a button - every sprite could be a button, right? - by setting an image as its background. But it didn't work.
I used the Empty_MonoGame_Example solution that I found among the examples, and did the same thing that I found in the BasicUI_MonoGame to include an image. In the XAML Designer I see what I would want to see as the end result, but in the running application there is nothing.
This is the XAML:
`<ek:UIRoot   xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:ek="clr-namespace:EmptyKeys.UserInterface.Designer;assembly=EmptyKeys.UserInterface.Designer"
             xmlns:c="clr-namespace:EmptyKeys.UserInterface.Designer.Charts;assembly=EmptyKeys.UserInterface.Designer"
             mc:Ignorable="d" 
             d:DesignHeight="640" d:DesignWidth="800">
    <Grid>
        <Button>
            <Button.Content>
                <Image>
                    <Image.Source>
                        <BitmapImage UriSource="Images/smiley.png" />
                    </Image.Source>
                </Image>
            </Button.Content>
        </Button>
    </Grid>
</ek:UIRoot>`

Could you please help with this? I attached the source code zip as well. Also: is it possible to adjust the hit test area to an arbitrary polygon? (Such as the silhouette of the sprite.)
[Empty_Example.zip](https://github.com/EmptyKeys/UI_Engines/files/2719469/Empty_Example.zip)
![missing_button](https://user-images.githubusercontent.com/32433870/50574662-d811d100-0dec-11e9-9d3d-67961c91a34d.png)

**Comment by mseress** [comment]
In the meantime I found the issue: I was missing the `ImageManager.Instance.LoadImages(Content);` from the LoadContent() method. So now that's working. But is there a possibility to clip a control to an arbitrary shape and use that for hit testing? It is possible in WPF:
`<Button Content="Hello" ClipToBounds="True" Width="200" Height="200" Name="MyButton" Click="MyButton_Click">
            <Button.Clip>
                <EllipseGeometry
                  RadiusX="100"
                  RadiusY="75"
                  Center="100,55"/>
            </Button.Clip>
        </Button>`

**Comment by EmptyKeys** [comment]
No, Clip is not supported.

**Comment by mseress** [comment]
I see. And is there any plan for it in the future?

**Comment by EmptyKeys** [comment]
No plans to support that for now. What are you trying to achieve?

**Comment by mseress** [comment]
Never mind, I will find a workaround. You can close this issue.

**Comment by mseress** [comment]
There are ways to work around this, not really relevant for now.
