### ISSUE TITLE
I think we can enhance the textBox

### ISSUE THREAD

**Issue by esengine** [EmptyKeys/UI_Engines#18]
Game.TextChanged can be captured on monogame's desktopgl to get the characters entered by the user, not just the normal 26 characters. I tested it can receive multiple bytes.

![image](https://user-images.githubusercontent.com/18465053/57497497-7ddccb80-730a-11e9-88ab-bff04ef7e3e3.png)

**Comment by EmptyKeys** [comment]
Hi, you can change that in this class

https://github.com/EmptyKeys/UI_Engines/blob/master/EmptyKeys.UserInterface.MonoGame/Input/MonoGameKeyboardState.cs

**Comment by esengine** [comment]
thanks
