### ISSUE TITLE
Nuget package includes wrong version of assembly

### ISSUE THREAD

**Issue by timesscar** [EmptyKeys/UI_Engines#19]
I noticed today after rebuilding my build server that the EmptykeysUI_Monogame nuget package includes version 3.0.0.0 of the EmptyKeys.UserInterface.Monogame assembly, but adds a reference to 3.1.0.0.  This behavior only seems to happen when installing the package fresh and not updating it.

![image](https://user-images.githubusercontent.com/10659660/57748243-f8507700-768d-11e9-89e9-b25d000b1327.png)

**Comment by timesscar** [comment]
Here is a project with a fresh 3.1 reference;  

![image](https://user-images.githubusercontent.com/10659660/57748413-b8d65a80-768e-11e9-9e7a-6ba0dc536422.png)

**Comment by timesscar** [comment]
And after downgrading then upgrading;  
![image](https://user-images.githubusercontent.com/10659660/57748462-defbfa80-768e-11e9-81af-91bca83aed7b.png)

**Comment by timesscar** [comment]
The actual assembly in the package;

![image](https://user-images.githubusercontent.com/10659660/57748525-369a6600-768f-11e9-81cb-8f3f0ca71281.png)

**Comment by timesscar** [comment]
Howdy, any chance you've had a moment to look at this?  Also, I noticed you merged the change request I put in a while back.  Will there be a new version of the nuget published at some point?  
Thanks again for your work! :)

**Comment by EmptyKeys** [comment]
new version is out

https://github.com/EmptyKeys/UI_Framework/releases/tag/3.2
