### ISSUE TITLE
can't seem to disable scrollbars on DataGrid component

### ISSUE THREAD

**Issue by ellisonch** [EmptyKeys/UI_Engines#2]
I'm trying to hide the scrollbars on a DataGrid component, but I can't seem to get it to work.

```
<DataGrid
    ScrollViewer.HorizontalScrollBarVisibility="Hidden"
    ItemsSource="{Binding DataGridData}"
>
```

The generator generates the code

```
this.e_4.HorizontalScrollBarVisibility = ScrollBarVisibility.Hidden;
```

and everything compiles without any sort of warning, but the scrollbars are still visible.  Using 'Auto' instead of 'Hidden' also doesn't seem to work, and I'd love to use 'Auto'.

Am I doing something wrong, or is there a bug?

**Comment by EmptyKeys** [comment]
Fixed. Auto is not implemented at this moment.
Thanks for report

**Comment by ellisonch** [comment]
Thanks!

Re: auto, it would be useful if the Library threw an exception/warning if you try and use features that are unimplemented.  Or, at least put that information in the comments.
