### ISSUE TITLE
Website down? How to get docs and how to pay?

### ISSUE THREAD

**Issue by ryancheung** [EmptyKeys/UI_Engines#20]
How to use EmptyKeys and how to pay this UI framework

**Comment by EmptyKeys** [comment]
Sorry, site is back.

Btw UI is for free, you don't have to pay. You can find docs here

https://emptykeys.github.io/UI_Framework/api/index.html

**Comment by ryancheung** [comment]
You mean empty keys UI now totally free now? I saw your earlier post that you had only open sourced two repos and leaved one for paying.

**Comment by EmptyKeys** [comment]
Hi, UI was always free, but only two parts are open source. You can get the UI on nuget.
