### ISSUE TITLE
Is There any change to make EmptyKeys support inputing CJK characters with a IME helper I made?

### ISSUE THREAD

**Issue by ryancheung** [EmptyKeys/UI_Engines#21]
I just create a universal(int most cases) IME helper for MonoGame:
https://github.com/ryancheung/MonoGame.IMEHelper

Is there any change for the user of EmptyKeys of EmptyKeys UI itself to integrate the IME Helper to support input for CJK characters?

And another question: How do EmptyKeys rendering the CJK texts, since MonoGame has no support for rendering dynamic fonts?

**Comment by EmptyKeys** [comment]
Hi, 
UI Framework is just set of components and controls. It's up to you how you use them.

Ad fonts, you would have to add that support to MonoGame or just use bitmap fonts. ~30k characters is enough for the game and it will not be that big.
