### ISSUE TITLE
can't get popups to work at all

### ISSUE THREAD

**Issue by ellisonch** [EmptyKeys/UI_Engines#3]
I wasn't sure if this belonged in the UI_Engines or UI_Generator, but this seemed more likely.

I can't seem to get Popups to show up at all.

```
<Popup
    IsOpen="{Binding CheatPopupOpen}"
    StaysOpen="True"
>
    <TextBlock>FooBarBaz</TextBlock>
</Popup>
```

The above popup generates code that compiles.  I have it reading a property `CheatPopupOpen` that is set to true.  Nothing shows up, no matter how many times I toggle that property.  I've tried moving things around and settings sizes and setting `Placement` as well, but no luck.

I wanted to try it with one of the basic examples found on the web, but they all use the unsupported `ElementName`.

Another (possibly related) problem is that if I try to set `IsOpen` to true directly (`IsOpen="True"`), the code that is generated sets it to false, not true:

```
this.e_6.IsOpen = false;
```

It's set to false if I set it to false as well.

**Comment by EmptyKeys** [comment]
No idea what's wrong, i would have to see more code not just few XAML lines. I use Popup a lot, but there could be some issues ofc. Check this XAML style - http://emptykeys.com/Community/aft/65 - how ComboBox is using it.

**Comment by ellisonch** [comment]
I made a small, self-contained test program for EmptyKeys + Monogame on windows.  I then branched and added the popup.  This can be found here: https://github.com/ellisonch/EmptyKeys_Basic/tree/popup
By looking at the changes in the branch, you can see what was added related to the popup.

In this example, I also cannot see a popup on the screen when I click the button.

**Comment by EmptyKeys** [comment]
I see, add Width and MaxHeight properties to Popup and It will work.

`<Popup Width="50" MaxHeight="50" ...`

I will think how to make it more WPFlike and without those properties.

**Comment by ellisonch** [comment]
Thanks!  This workaround works for me.

I never would have figured that out though.  I had even tried using width and height properties earlier, but that's not enough.  For some reason, only maxheight works.

**Comment by EmptyKeys** [comment]
Changes done, still some placement modes are just little bit different from WPF. Good enough for now tho. Changes are in next version.
