### ISSUE TITLE
Mouse Clicks affect out-of-focus MonoGame windows

### ISSUE THREAD

**Issue by andrewjoy** [EmptyKeys/UI_Engines#5]
This is easily reproducible with the MonoGame example project. Position the window so you know where the button is on-screen, then bring another window to the front and click on it where the button is now obscured by the new window. The audio effect plays and the progress bar increments. This doesn't happen in at least the CocosSharp example project.

**Comment by EmptyKeys** [comment]
Yeah, that's bug in MonoGame 3.4 not sure if they fixed it already or not. You can try develop version and if it's still an issue, report it to MonoGame team pls. BTW CocosSharp is using MonoGame too and it's probably newer version. That's why it's working fine.

**Comment by andrewjoy** [comment]
Ah, gotcha. Thanks for the quick reply! This should fix itself then as they push out a new version, so I'll close the issue.
