### ISSUE TITLE
button and slider value

### ISSUE THREAD

**Issue by ghost** [EmptyKeys/UI_Engines#6]
Hi,

i have looked into the examples, but, i am not very familar with partialclasses and so on (ansi-c for microcontroller background).
so my question is, how do i read the state of the button and the value of a slider in the very simple way (like in windows form projects or as simple variable)?

Greetings 
Daniel

**Comment by EmptyKeys** [comment]
Set Name attribute on your button in XAML. Create partial class in the same namespace and with the same name like generated UI class. Create property to access private member with that name.

You can see this in examples (property Fill) - https://github.com/EmptyKeys/UI_Examples/blob/master/BasicUI_MonoGame/GameUILibrary/GeneratedUI/TetrisBlock.cs
