### ISSUE TITLE
Question : how did you fix "Internal compiler error: Sequence contains no matching element"

### ISSUE THREAD

**Issue by StefH** [EmptyKeys/UI_Engines#8]
In this post http://emptykeys.com/Community/aft/142 , a user reported an issue.

Can you please explain the issue which you created at MS or describe the fix ?

**Comment by EmptyKeys** [comment]
I sent MS repro for .NET Native compiler. The issue was that they expect some internal value name in IL on enum and my post compile renamer was changing that name. So I fixed renamer tool to ignore that.
