### ISSUE TITLE
MissingMethodException in nuget package EmptyKeysUI_Xenko

### ISSUE THREAD

**Issue by EnoughTea** [EmptyKeys/UI_Engines#9]
Hello!

Fresh install of EmptyKeys on latest Xenko 1.9.3-beta throws a MissingMethodException when trying to draw anything, because `XenkoRenderer` cannot call a `SpriteBatch.Draw` overload.

I assumed it was an assembly binding error and peeked at `EmptyKeys.UserInterface.Xenko.dll` in Reflector. It wants to bind `SiliconStudio.Xenko.Graphics.dll` `1.9.0.0` from older Xenko 1.9.0. However, in runtime it binds with `SiliconStudio.Xenko.Graphics.dll` `1.9.3.0` from Xenko 1.9.3. 

Looks like building UI_Engines from source is impossible without the closed part of EmptyKeys, so what is the recommended course of action?

##Steps to reproduce:
1) Create empty Xenko project.
2) Add `EmptyKeysUI_Xenko` references to both Game and Windows project.
3) Add missing shaders for SDF fonts to a Game project.
4) Initialize EmptyKeysUI and wire up a `SceneDelegateRenderer` for drawing.
5) Draw a basic `UIRoot` with anything, e.g. a single `TextBlock` inside the `SceneDelegateRenderer`.

##Exception details:
```
System.MissingMethodException occurred
  HResult=-2146233069
  Message=Method not found: 'Void SiliconStudio.Xenko.Graphics.SpriteBatch.Draw(SiliconStudio.Xenko.Graphics.Texture, SiliconStudio.Core.Mathematics.RectangleF, SiliconStudio.Core.Mathematics.Color4)'.
  Source=EmptyKeys.UserInterface.Xenko
  StackTrace:
       at EmptyKeys.UserInterface.Renderers.XenkoRenderer.Draw(TextureBase texture, PointF position, Size renderSize, ColorW color, Boolean centerOrigin)
       at EmptyKeys.UserInterface.Media.SolidColorBrush.Draw(TextureBase texture, Renderer renderer, Double elapsedGameTime, PointF position, Size renderSize, Single opacity)
```

**Comment by EmptyKeys** [comment]
It's renamed namespace issue. I updated sources so you can compile it now.

You don't need any closed part of the UI. Everything needed is here in this repository.

Try it now and let me know if you have any problem.

**Comment by EnoughTea** [comment]
Oops, I assumed `EmptyKeys.UserInterface.dll` has to be rebuild as well.

Tried it now, looks like everything works fine, thanks!
